apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1   # ✅ IMPORTANT: only 1 for SQLite
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: yogitaaher/api-gateway
        ports:
        - containerPort: 8000
        env:
        - name: BREACH_SCANNER_URL
          value: "http://breach-scanner:8001"
        - name: GITHUB_SCANNER_URL
          value: "http://github-scanner:8002"
        - name: RISK_ANALYZER_URL
          value: "http://risk-analyzer:8003"

        # ✅ ADD THIS (mount volume)
        volumeMounts:
        - name: api-storage
          mountPath: /app/data

      # ✅ ADD THIS (connect PVC)
      volumes:
      - name: api-storage
        persistentVolumeClaim:
          claimName: api-gateway-pvc